"""
File: TwoDicePractice.py
------------------
Simulate rolling two dice, and prints results of each
roll as well as the total.
"""
import random

def main():
    roll_dice()

def roll_dice():
    """
    Uses randint with a min of 1 and a max of 6 with two variables
    named die1 and die2 to simulate a dice roll. Prints the values
    generated by each individual dice as well as the sum of the two
    values.
    PRE: none
    POST: All values have been printed
    """
    die1 = random.randint(1, 6)
    die2 = random.randint(1, 6)
    total = die1 + die2
    print(f'Dice 1 rolled a: {die1}\nDice 2 rolled a: {die2}\nThe total is: {total}')


# This provided line is required at the end of a Python file
# to call the main() function.
if __name__ == '__main__':
    main()